// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Styles$ReactHooksTemplate = require("./Styles.bs.js");

function useCounter(param) {
  return React.useReducer((function (state, action) {
                if (action) {
                  return /* record */[
                          /* count */state[/* count */0],
                          /* show */!state[/* show */1]
                        ];
                } else {
                  return /* record */[
                          /* count */state[/* count */0] + 1 | 0,
                          /* show */state[/* show */1]
                        ];
                }
              }), /* record */[
              /* count */0,
              /* show */true
            ]);
}

function Component3(Props) {
  var greeting = Props.greeting;
  "You've clicked this " + (String(1) + " times(s)");
  return React.createElement("h1", {
              className: Styles$ReactHooksTemplate.actionButton(false)
            }, greeting);
}

var make = Component3;

exports.useCounter = useCounter;
exports.make = make;
/* react Not a pure module */
