// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Styles$ReactHooksTemplate = require("./Styles.bs.js");

function Component2(Props) {
  var greeting = Props.greeting;
  var match = React.useState((function () {
          return 0;
        }));
  var changeCounter = match[1];
  return React.createElement("div", undefined, React.createElement("button", {
                  className: Styles$ReactHooksTemplate.title,
                  onClick: (function (_event) {
                      return Curry._1(changeCounter, (function (counter) {
                                    return counter + 1 | 0;
                                  }));
                    })
                }, greeting), String(match[0]));
}

var make = Component2;

exports.make = make;
/* react Not a pure module */
