// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Component3$ReactHooksTemplate = require("../src/Component3.bs.js");

Jest.describe("Events", (function (param) {
        Jest.test("toggleEvent should toogle state.show", (function (param) {
                var state = Component3$ReactHooksTemplate.on_toggle(Component3$ReactHooksTemplate.initialState);
                Jest.Expect[/* toBe */2](false, Jest.Expect[/* expect */0](state[/* show */1]));
                var state$1 = Component3$ReactHooksTemplate.on_toggle(state);
                return Jest.Expect[/* toBe */2](true, Jest.Expect[/* expect */0](state$1[/* show */1]));
              }));
        return Jest.test("clickEvent should add 1 to state.count", (function (param) {
                      var state = Component3$ReactHooksTemplate.on_click(Component3$ReactHooksTemplate.initialState);
                      Jest.Expect[/* toBe */2](1, Jest.Expect[/* expect */0](state[/* count */0]));
                      var state$1 = Component3$ReactHooksTemplate.on_click(state);
                      return Jest.Expect[/* toBe */2](2, Jest.Expect[/* expect */0](state$1[/* count */0]));
                    }));
      }));

/*  Not a pure module */
